# This action runs the Selenium automated tests

name: UI Automated Testing
on:
  push:
    branches: [ "Selenium_UI_test" ]
  pull_request:
    branches: [ "Selenium_UI_test" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Add VSTest.console.exe to the PATH
        uses: darenm/Setup-VSTest@v1

      - name: Run functional tests
        run: vstest.console.exe ${{ github.workspace }}\Selenium_Nunit_UI_Test\bin\Debug\net6.0\Selenium_Nunit_UI_Test.dll
